
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    control-plane: controller-manager
